- app/assets/javascripts/bp_annotator.js
- app/controllers/annotator_controller.rb
- app/views/annotator/index.html.haml
The links "To reproduce these results: " and "Format Results As: JSON" generated by the annotator UI are wrong
When the "Match Partial Words" box is checked, then it generates a link with the parameter whole_word_only sets to true (it would need to be set to false). 
And when the "Match Partial Words" box is unchecked, then it generates a link with the parameter whole_word_only sets to false
It is just a confusion caused by the fact that the parameter has the opposite semantic in the REST API and in the UI
Also fix a bug where the context column stayed hidden if no context was found in the previous annotation request
> Fix wrong annotator REST API link

- public/javascripts/bp_ontology_viewer.js
When Google analytics is not used on a appliance and the /analytics JSON is empty an uncaught error is raised by bp_ont_chart.js : Uncaught TypeError: Cannot read property 'getContext' of null
This error cause some trouble with the UI (impossible to directly go from the summary tab to the classes tab. A reload of the page is needed) 
So we have just surrounded the ontology visit charts init with try/catch
> Fix UI problem caused by empty visits charts

- app/assets/javascripts/bp_annotator.js
Before it was not working when there was a single quote ( ' ) in the text to annotate. I just changed how the link was declared in the javascript
> Fix generation of 'Format results as' links in Annotator

- app/controllers/ontologies_controller.rb
- app/views/ontologies/browse.html.erb
For SKOS ontologies now display number of individuals (representing number of concepts) instead of the number of classes in the browse section
> In browse: for SKOS ontologies now display number of individuals

- config/bioportal_config_env.rb.sample
- lib/log.rb
API v3 used to have an endpoint for accepting remote log entries. This is no longer in place so remote logging needs to be removed.
Addresses #213
> Remove deprecated remote logging

- Gemfile
- Gemfile.lock
- app/assets/javascripts/bp_ontology_viewer.js.erb
- app/controllers/ontologies_controller.rb
- app/views/layouts/_ontology_viewer.html.haml
- app/views/ontologies/_metadata.html.haml
- app/views/ontologies/visualize.html.haml
- config/bioportal_config_env.rb.sample
- config/initializers/ontologies_api_client.rb
- config/settings.yml
* Bumps [ontologies_api_client](https://github.com/ncbo/ontologies_api_ruby_client) from 2.2.2 to 2.2.4
* Converts $PURL_ENABLED and $PURL_PREFIX environment variables to YAML configuration in `settings.yml`
* Removes textual references to permalinks in the class Details pane. Resolves #274.
> Code refactoring for issues with class permalinks

- app/controllers/admin_controller.rb
- Fixes a number of "can't modify frozen string" errors, thrown from the AdminController after the upgrade to Ruby 3
- Fixes a "wrong number of arguments" error thrown by the AdminController when attempting to delete ontologies. This was a regression caused by some RuboCop linting.
- Resolves #287
> Fix issues in the Admin Console with ontology and submission deletion

- app/assets/javascripts/bp_notes.js
- app/controllers/subscriptions_controller.rb
- app/helpers/application_helper.rb
- app/helpers/notes_helper.rb
- app/views/users/show.html.haml
- Fixes #298
- Fixes #300
- Fixes `Uncaught TypeError` that prevents link text toggle on notes emails subscribe / unsubscribe
- Refactors the `subscribed_to_ontology?` method do account for user objects with unloaded subscription attributes
- Fixes some RuboCop warnings
> Fix various issues with notes emails subscriptions

- app/controllers/users_controller.rb
- app/views/users/show.html.haml
This PR resolves an issue where a misleading error message was shown following the successful save of a custom ontology set (#330). Additional updates include:
* Replace deprecated `find` with `get` in `UsersController#custom_ontologies`
* Apply the correct flash message style for error notifications during custom ontology set save operations
* Improve the text content of flash notice and error messages when modifying custom ontology sets
* Tweak the list style for custom ontology set lists to improve appearance
> Fix misleading error message after custom ontology set save

- .env.sample
- test/controllers/ontologies_controller_test.rb
Provide the ability to specify a list of ontologies to test instead of testing all ontologies. This is useful when testing APIs with a large number of ontologies.
> Add option to test a specific set of ontologies

- app/controllers/ontologies_controller.rb
- app/controllers/projects_controller.rb
Render 404 status for non-existing ontologies and projects.
Note: A 404 status is also returned when private ontologies are accessed without the required privileges. This behavior could be enhanced in the future to display a custom message.
Addresses: [ncbo/bioportal_web_ui#334](https://github.com/ncbo/bioportal_web_ui/issues/334)
> Fix: Render 404 for non-existing ontologies and projects

- app/assets/stylesheets/bootstrap_overrides.scss
- app/views/layouts/_footer.html.haml
- config/locales/en.yml
- config/settings.yml
This pull request introduces modifications to the footer to align with requirements for an upcoming NAR proposal submission for a BioPortal paper.
- Adds a statement that BioPortal is free and open to all users
- Adjusts the footer height slightly to accommodate this new statement
- Adds a translation for the "free and open" statement to in the `en.yml` file to support internationalization
- Adds a new "Use of Cookies" link to the collection of footer links
- Updates `settings.yml` to store the physical URL for the section in BioPortal’s Terms of Use that describes the application’s use of cookies
> Footer updates: free access notice and use of cookies link

- Gemfile.lock
- app/assets/stylesheets/concepts.scss
- app/controllers/change_requests_controller.rb
- app/helpers/change_requests_helper.rb
- app/javascript/controllers/change_requests_controller.js
- app/lib/kgcl/issue_content_generator.rb
- app/lib/kgcl/operations.rb
- app/lib/kgcl/renderers/edit_definition_content.rb
- app/lib/kgcl/templates/edit_definition_body.erb
- app/lib/kgcl/templates/edit_definition_title.erb
- app/services/issue_creator_service.rb
- app/views/change_requests/_edit_definition.html.haml
- app/views/change_requests/_node_obsoletion.html.haml
- app/views/change_requests/_node_rename.html.haml
- app/views/change_requests/_notice.html.haml
- app/views/change_requests/create.js.erb
- app/views/change_requests/create.turbo_stream.haml
- app/views/change_requests/edit_definition.turbo_stream.haml
- app/views/concepts/_details.html.haml
- config/change_request.yml
- config/routes.rb
This pull request introduces several enhancements and improvements to the change request process. It adds support for the [TextDefinitionReplacement](https://incatools.github.io/kgcl/TextDefinitionReplacement/) change request type, enabling users to request modifications to the definitions of ontology classes.
Additionally, it improves error handling by addressing cases where users provide an invalid GitHub repository name or attempt to use a repository with the issue tracker disabled.
The code responsible for hiding change request forms on Cancel and Submit actions has been refactored to be more generic and reusable, ensuring consistency across all change request forms, regardless of type.
Changes to the `concepts/_details` partial were intentionally kept minimal, with the knowledge that …
> Implement the TextDefinitionReplacement ontology change request type

- app/assets/stylesheets/account.scss
- app/controllers/home_controller.rb
- app/controllers/login_controller.rb
- app/controllers/users_controller.rb
- app/helpers/sessions_helper.rb
- app/views/layouts/_topnav.html.haml
- app/views/users/show.html.haml
- config/routes.rb
- Removed the `home#account` route in favor of consistently using `users#show` throughout the codebase for navigating to the account settings page
- Refactored `UsersController#show` to reduce REST calls for fetching ontologies from two to one
- Used `sort_by` instead of `sort!` in `UsersController#show` for better performance
- Introduced `SessionsHelper#welcome_message` to compose the welcome message upon login, allowing for cleaner code in `LoginController#login`
- Updated the Projects and Ontologies sections on the account settings page to use a CSS Flexbox layout, improving readability for admin users managing many projects/ontologies
- Replaced plain anchor links with chip button components for project and ontology items
> Account settings page refactors and navigation cleanup

- app/controllers/admin_controller.rb
- Refactored `update_info` method to always assign @update_info, even if the API response includes an "error" key.
- Ensured that partial failures (e.g., update check error) do not prevent access to valid fields like appliance_id.
- Updated method to use a keyword argument (`render_response: true`) instead of a positional boolean, improving readability and satisfying Rubocop guidelines. 
relates to https://github.com/ontoportal/ontoportal-project/issues/59
> Fix update_info behavior to preserve appliance_id on partial API errors

- app/components/submission_metadata_component/submission_metadata_component.html.haml
- app/helpers/ontologies_helper.rb
Resolves https://github.com/ncbo/bioportal_web_ui/issues/430. There was a reference to the @submission object without a check for its validity. There was also a bug in the method that displays the "Download" button.
> Resolves the issue with displaying ontologies with no submissions (#430)

- Capfile
- Gemfile
- config/deploy.rb
- config/deploy/appliance.rb
- config/deploy/production.rb
- config/deploy/staging.rb
- config/newrelic.yml
- lib/capistrano/tasks/config.rake
- lib/capistrano/tasks/newrelic.rake
Refactor of Capistrano deployment:
- Move logic out of config/deploy.rb into capistrano tasks 
- Add Capistrano task for notifying NewRelic of deployments.
- Remove encrypted credentials from newrelic.yml
- Disable NewRelic agent in appliance
Notes:
Encrypted credentials do not work in newrelic.yml, since the file is parsed before Rails initializes. As a result, Rails.application.credentials is not accessible at that point. 
The NewRelic Capistrano announce task is disabled by default. To enable it, add the following to your environment-specific deploy config:
```
set :newrelic_notice_enabled, true
```
> Add Capistrano Task to Announce Deployments in New Relic

- app/assets/stylesheets/bioportal.scss
- app/assets/stylesheets/theme-variables.scss.erb
Replaced hardcoded colors for the login button and navbar with theme variables.
Reason: When running in appliance mode, the ontoportal theme wasn't correctly applying the navbar color due to hardcoded values.  
Fixes https://github.com/ncbo/bioportal_web_ui/issues/425
> Use theme variables for login button and navbar styles

- app/views/mappings/_show.html.haml
This PR resolves https://github.com/ncbo/bioportal_web_ui/issues/452, which was affecting many ontologies, not just OMO and AERO.
To reproduce the issue, navigate to https://bioportal.bioontology.org/ontologies/NCIT?p=mappings and click on any of the mapping links. The links inside the mapping table will be reversed.
> Bugfix: mappings between two ontologies show links that are reversed

- app/assets/stylesheets/components/tree_view.scss
- app/components/dropdown_container_component/dropdown_container_component.html.haml
- app/components/language_field_component/language_field_component.html.haml
- app/components/tree_link_component.rb
- app/components/tree_view_component.rb
- app/helpers/ontologies_helper.rb
- app/views/layouts/_notices.html.haml
- app/views/mappings/_show.html.haml
- app/views/ontologies/properties.html.haml
The code recently contributed by AgroPortal uses an older version of Bootstrap, 4.x, while ours is a newer version, 5.x. 
In Bootstrap, certain style naming conventions changed from 4.x to 5.x (ex: "pl-3", padding-left-3 changed to "ps-3", padding-start-3, so the correct style wasn’t kicking in in the version you’re seeing. This PR addresses this issue, which affected the class tree display.
Tree with the bug:
Tree fixed:
> Bugfix: class tree display indentations and bootstrap 5 compatibility
